language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mohamedsaihi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohamedsaihi/react-test npm test

after_success:
  - docker build -t mohamedsaihi/multi-client ./client
  - docker build -t mohamedsaihi/multi-nginx ./nginx
  - docker build -t mohamedsaihi/multi-server ./server
  - docker build -t mohamedsaihi/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those Images and push them to Docker Hub
  - docker push mohamedsaihi/multi-client
  - docker push mohamedsaihi/multi-nginx
  - docker push mohamedsaihi/multi-server
  - docker push mohamedsaihi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-654654318632"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY